name: Build Nightly APK

on:
  push:
    branches: [ "beta" ]
  workflow_dispatch:

jobs:

  build:
    name: Build Nightly APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get application version name
        run: echo "VERSION_NAME=nightly-$(($(cat app/build.gradle.kts | grep versionCode | tr -s ' ' | cut -d " " -f 4 | tr -d '\r')))" >> $GITHUB_ENV

      - name: Bump application version code
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionName: "${{ env.VERSION_NAME }} (#${{github.run_number}})"

      - name: Write sign info
        if: github.repository == 'DHD2280/Oxygen-Customizer'
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi

      - name: Build with Gradle
        if: github.repository == 'DHD2280/Oxygen-Customizer'
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        if: github.repository == 'DHD2280/Oxygen-Customizer'
        uses: actions/upload-artifact@v4
        with:
          name: "Oxygen Customizer ${{ env.VERSION_NAME }} Dev (#${{github.run_number}})"
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Zip artifact for deployment
        run: zip OxygenCustomizer.zip ./app/build/outputs/apk/release/*.apk -r

      - name: Telegram File Attachment
        if: github.repository == 'DHD2280/Oxygen-Customizer'
        run: |
          curl -v "https://api.telegram.org/bot${{ secrets.TELEGRAM_TK }}/sendMediaGroup" \
            -F chat_id=${{ secrets.OC_NIGHTLY_BUILDS }} \
            -F media='[{"type":"document", "media":"attach://Xposed", "caption":"Oxygen Customizer ${{ env.VERSION_NAME }} Dev (#${{github.run_number}})"}]' \
            -F Xposed="@OxygenCustomizer.zip"
